manifest_version: "1"

clouds:
  - name: "azure"
    environments: ["dev", "test", "prod"]
  - name: "gcp"
    environments: ["dev", "test", "prod"]
  - name: "private-cloud"
    environments: ["dev", "test", "prod"]
