manifest_version: "1"

settings:
  enable_componnent: false
  enable_deletion_protection: false
  repave_mode: true

base_spaces:
  - name: "modules"
    enabled: true
    description: "Reusable code registry"
  - name: "customer"
    enabled: true
    description: "Managed workload container"
  - name: "sandbox"
    enabled: true
    description: "Experimentation and scratch space"

clouds:
  - name: "azure"
    enabled: true
    environments: ["dev", "test", "prod"]
  - name: "gcp"
    enabled: true
    environments: ["dev", "test", "prod"]
  - name: "private-cloud"
    enabled: true
    environments: ["dev", "test", "prod"]
