manifest_version: "1"

settings:
  enable_component: true
  enable_deletion_protection: true
  repave_mode: false

base_spaces:
  - name: "modules"
    enabled: false
    description: "Reusable code registry"
  - name: "customer"
    enabled: false
    description: "Managed workload container"
  - name: "sandbox"
    enabled: false
    description: "Experimentation and scratch space"

clouds:
  - name: "azure"
    enabled: false
    environments: ["dev", "test", "prod"]
  - name: "gcp"
    enabled: false
    environments: ["dev", "test", "prod"]
  - name: "private-cloud"
    enabled: false
    environments: ["dev", "test", "prod"]
